import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('./app/page.tsx',import.meta.url),'utf8');
const body=source.match(/function recommend\(a:string\[\]\)\{(.*?)\}/s)[1];
const recommend=new Function('a',body);
assert.equal(recommend(['博士']),3);
assert.equal(recommend(['硕士','','还没确定']),0);
assert.equal(recommend(['本科','','英国','','','','已有文书草稿']),2);
assert.equal(recommend(['硕士','','香港金融','','','','选校定位']),1);
assert.equal(recommend([]),1);
console.log('Assessment routing checks passed');
